### ISSUE TITLE
It should use "〇" to represent "0" in year in simplified Chinese

### ISSUE THREAD

**Issue by chirsz-ever** [magiclen/chinese-lunisolar-calendar#2]
根据《中华人民共和国国家标准 出版物上数字用法》（GB/T 15835—2011）的 5.2.5 节，大陆简体在使用汉字表示年份时应当使用“〇”：

![图片](https://user-images.githubusercontent.com/31474766/108519213-6666ab00-7304-11eb-9a8f-3c57128dbfa8.png)

当然，这是一份用于出版物的建议性标准（`GB/T` 而非 `GB`），或许可以用一个选项进行控制？或者提供像 `strftime` 那样的 API 用来自定义输出格式？

**Comment by magiclen** [comment]
26de30d55cee6ccc4db952bf0de6641a50d643c6 為不更動原有的API，暫時先以新的方法來以`〇`表示數字`0`

e.g.

```rust
let solar_date = SolarDate::from_naive_date(NaiveDate::from_ymd(2019, 1, 15)).unwrap();
assert_eq!("二〇一九年一月十五日", solar_date.to_chinese_string_2());
```

**Comment by magiclen** [comment]
目前的版本已使用`〇`。
