### ISSUE TITLE
baizi weight 是做什么的？

### ISSUE THREAD

**Issue by ZhangHanDong** [magiclen/chinese-lunisolar-calendar#4]
传统八字好像没有听说过有这个 权重啊

**Comment by magiclen** [comment]
可參考[百度百科](https://baike.baidu.com/item/%E8%A2%81%E5%A4%A9%E7%BD%A1%E7%A7%B0%E9%AA%A8%E6%AD%8C)。

**Comment by ZhangHanDong** [comment]
了解
